/**
 * Context Injector
 *
 * For each agent with active tasks, writes a CONTEXT.md to their instruction
 * root folder. The file is small (< 600 tokens) and contains only what's
 * relevant to current work.
 *
 * Agents pick it up naturally on next heartbeat via instructionsBundleMode="external".
 * No changes needed to agent configs.
 */

import fs from 'fs'
import path from 'path'
import { query } from './db.ts'
import { config } from './config.ts'
import { readForAgent, searchByKeywords } from './wiki/store.ts'

interface AgentTask {
  agentId: string
  agentName: string
  agentSlug: string
  instructionsRoot: string
  tasks: Array<{ identifier: string; title: string; status: string }>
}

export async function getAgentsWithTasks(): Promise<AgentTask[]> {
  const rows = await query<{
    agent_id: string
    agent_name: string
    instructions_root: string | null
    identifier: string
    title: string
    status: string
  }>(`
    SELECT
      a.id            AS agent_id,
      a.name          AS agent_name,
      (a.adapter_config->>'instructionsRootPath') AS instructions_root,
      i.identifier,
      i.title,
      i.status
    FROM issues i
    JOIN agents a ON a.id = i.assignee_agent_id
    WHERE i.company_id = $1
      AND i.status IN ('todo', 'in_progress', 'blocked')
      AND i.assignee_agent_id IS NOT NULL
    ORDER BY a.name, i.status DESC
  `, [config.companyId])

  // Group by agent
  const byAgent = new Map<string, AgentTask>()
  for (const row of rows) {
    if (!row.instructions_root) continue

    if (!byAgent.has(row.agent_id)) {
      byAgent.set(row.agent_id, {
        agentId: row.agent_id,
        agentName: row.agent_name,
        agentSlug: row.agent_name.toLowerCase().replace(/\s+/g, '-'),
        instructionsRoot: row.instructions_root,
        tasks: [],
      })
    }
    byAgent.get(row.agent_id)!.tasks.push({
      identifier: row.identifier,
      title: row.title,
      status: row.status,
    })
  }

  return Array.from(byAgent.values())
}

export async function injectContext(agent: AgentTask): Promise<void> {
  const contextPath = path.join(agent.instructionsRoot, 'CONTEXT.md')

  // Build keyword list from task titles
  const keywords = agent.tasks
    .flatMap(t => t.title.toLowerCase().split(/[\s\-_/]+/))
    .filter(k => k.length > 3)
    .slice(0, 12)

  // Pull relevant wiki entries
  const agentEntries = readForAgent(agent.agentSlug, 3)
  const topicEntries = searchByKeywords(keywords, 4)

  // Deduplicate
  const seen = new Set<string>()
  const allEntries = [...agentEntries, ...topicEntries].filter(e => {
    if (seen.has(e.filePath)) return false
    seen.add(e.filePath)
    return true
  })

  const content = buildContextFile(agent, allEntries)

  // Only write if content changed
  const existing = fs.existsSync(contextPath) ? fs.readFileSync(contextPath, 'utf8') : ''
  if (content === existing) return

  fs.mkdirSync(agent.instructionsRoot, { recursive: true })
  fs.writeFileSync(contextPath, content, 'utf8')
  console.log(`[injector] ${agent.agentName}: CONTEXT.md updated (${content.length} chars)`)
}

export async function runInjection(): Promise<void> {
  const agents = await getAgentsWithTasks()

  if (agents.length === 0) {
    console.log('[injector] no agents with active tasks')
    return
  }

  for (const agent of agents) {
    await injectContext(agent)
  }

  console.log(`[injector] done — ${agents.length} agent(s) updated`)
}

// ── Build the CONTEXT.md content ─────────────────────────────────────────────

function buildContextFile(
  agent: AgentTask,
  wikiEntries: ReturnType<typeof readForAgent>
): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ')
  const lines: string[] = []

  lines.push(`<!-- auto-generated by mi1k-middleware ${now} — do not edit manually -->`)
  lines.push(`# Current Context for ${agent.agentName}`)
  lines.push('')

  // Active tasks
  lines.push('## Your Active Tasks')
  for (const task of agent.tasks) {
    const badge = task.status === 'in_progress' ? '🔵' : task.status === 'blocked' ? '🔴' : '⚪'
    lines.push(`- ${badge} **${task.identifier}**: ${task.title} *(${task.status})*`)
  }
  lines.push('')

  // Wiki knowledge relevant to current work
  if (wikiEntries.length > 0) {
    lines.push('## Relevant Knowledge')
    for (const entry of wikiEntries.slice(0, 4)) {
      // Include title and first 400 chars of body only — keep context small
      const bodySnippet = entry.body.replace(/^#.*$/m, '').trim().slice(0, 400)
      lines.push(`### ${entry.title}`)
      if (bodySnippet) lines.push(bodySnippet)
      lines.push('')
    }
  }

  return lines.join('\n')
}
